### PR TITLE
adding js for outputting everything to screen

### PR DESCRIPTION
**Pull request by ashwoodaa**

### CODE REVIEW

**Comment by ashwoodaa** [comment]
Dog info is not showing up but other than that it looks great

**Comment by ashwoodaa** [comment]
Thanks, me!

**Comment by ashwoodaa** [comment]
No problem! bitmoji

**Comment by ashwoodaa** [comment]
Dog food is now showing up. It was that you can not make comments in JSON.

**Comment by ashwoodaa** [comment]
Done

**Comment by gregkorte** [comment]
Nice job on your quiz, Amari! For challenge mode figure out how to refactor your code by breaking your for loops into separate functions. See how DRY you can make it. :+1:  You are good to merge otherwise. Keep up the good work!

**Comment by ashwoodaa** [comment]
Thanks!!! I'll put the challenge mode thing on my to-do list.
Hope you have a good day!

**Pull request merged**
